spring:
  datasource:
    #    url: jdbc:h2:mem:testh2 # 이게 인메모리 방식이라 서버 재실행하면 데이터 사라진다.
    #    url: jdbc:postgresql://localhost:5432/testdb1  # postgresql
    url: jdbc:postgresql://localhost:6432/jwtRedis # agensgraph2(도커 컨테이너 이름)
    username: test1
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4
#  h2:
#    console:
#      enabled: true # 이걸 해야지만 h2-console 로그를 h2 안키고 접속할 수 있다.
  jpa:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLdialect
    hibernate:
      ddl-auto: create # SessionFactory 시작시 스키마를 삭제하고 다시 생성
    properties:
      hibernate:
        # show_sql: true # jpa가 실행하는 쿼리를 콘솔에 찍는다.
        format_sql: true  # 쿼리가 format돼서 예쁘게 나온다.
    database: postgresql
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: localhost
    password: '1234'

jwt:
  header: Authorization
  secret-key: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token:
    expired-time-ms: 86400 # token만료시간을 86400초(24시간)로 설정한다

logging.level:
  org.hibernate.SQL: debug